Feature/axes and movements
yuydev-ru/engine pull request #7
Opened 2021-07-09 13:34 UTC by MichaelX-code

2021-07-09 14:01 UTC, saintruler requested changes

2021-07-09 20:48 UTC, saintruler requested changes

2021-07-09 20:48 UTC, saintruler commented on base.cpp
> +    };
Придерживайтесь оформления как в остальном проекте.
```cpp
config->axisData = { { sf::Keyboard::Key::W, KeyData("vertical", "hold", 1) }
                   , { sf::Keyboard::Key::S, KeyData("vertical", "hold", -1) }
                   ...
                   , {sf::Keyboard::Key::Space, KeyData("", "push", 0)}
                   };
```

2021-07-09 20:48 UTC, saintruler commented on base.h
> +                                                  , {"vertical", 0} };
В этом месте структура тоже иницализирутеся с какими-то конкретными осями. Это должно происходить в другом месте, например, в `loadConfig`, как и в остальных случаях.

2021-07-10 06:51 UTC, MichaelX-code commented on base.h
> +                                                  , {"vertical", 0} };
Стоит определить инициализацию или только определение конкретных осей?
axes обновляется каждый кадр, и я не очень понимаю, почему мы тогда должны хранить это в конфиге.

2021-07-10 07:00 UTC, saintruler commented on base.h
> +                                                  , {"vertical", 0} };
Заполнение этого словаря осями должно происходить не здесь, так как все названия осей задаются в конфиге и там может вообще не оказаться horizontal и vertical.

2021-07-10 07:11 UTC, saintruler requested changes

2021-07-10 07:11 UTC, saintruler commented on base.cpp
> +    bool isPushed = false;
Всё же с одной переменной на все push кнопки есть проблема. Да, механик на одновременное нажатие двух push кнопок скорее всего не будет. Но, допустим, есть две push кнопки: F и E. Если E была нажата и не отпускается, то нельзя будет нажать на F в это время. Это выглядит как баг.

2021-07-10 19:22 UTC, saintruler approved these changes

2021-07-10 19:25 UTC, merged